package com.rt.mapper;

import com.rt.dto.ReqUserDTO;
import com.rt.entity.User;

public class UserMapper {

    // Convert User entity to ReqUserDTO
    public static ReqUserDTO toDTO(User user) {
        if (user == null) {
            return null;
        }
        ReqUserDTO dto = new ReqUserDTO();
        dto.setName(user.getName());
        dto.setMobile(user.getMobile());
        dto.setEmail(user.getEmail());
        dto.setAddress(user.getAddress());
        dto.setPassword(user.getPassword());
        dto.setRole(user.getRole()); // ✅ Add role mapping
        return dto;
    }

    // Convert ReqUserDTO to User entity
    public static User toEntity(ReqUserDTO dto) {
        if (dto == null) {
            return null;
        }
        User user = new User();
        // id is not set here because it's autogenerated
        user.setName(dto.getName());
        user.setMobile(dto.getMobile());
        user.setEmail(dto.getEmail());
        user.setAddress(dto.getAddress());
        user.setPassword(dto.getPassword());
        user.setRole(dto.getRole()); // ✅ Add role mapping
        return user;
    }
}
